* config

  My dotfiles for working with Elixir

** Usage

   This repo is a collection of [[https://thewanderingcoder.com/2015/02/literate-emacs-configuration/][literate]] configuration files.

   Open each =.org= file in Emacs and use ~M-x org-babel-tangle~ to provision
   your machine with its configuration.

   *WARNING*: ~M-x org-babel-tangle~ will overwrite any existing configuration
   files already present on your machine. In the case of =bash.org=, this would
   rewrite your =~/.bash_profile= and =~/.bashrc= files.

** Install

   Link [[file:.spacemacs][.spacemacs]] to your =$HOME= directory to include any future changes
   automatically.

   #+BEGIN_SRC sh :export none
     ln -s "$(git rev-parse --show-toplevel)/.spacemacs" ~/.spacemacs
   #+END_SRC

   Running =emacs.org= will create layers under =~/.emacs.d/private=, but some
   subdirectories *MUST* be added manually:

   #+BEGIN_SRC sh :export none
     mkdir -p ~/.emacs.d/private/my-{elixir,org}
   #+END_SRC

   Some of the =.org= files include =Installation= sections. These manual, one-time
   steps are suggested to ensure everything just works (TM).
